### ISSUE TITLE
Doesn't work properly on G2

### ISSUE THREAD

**Issue by guidoferreyra** [mekkablue/FixZeroHandles#1]
Hi!
I've tested with the same paths on both versions of Glyphs, and in G1 works well but in G2 doesn't do the job.

**Comment by mekkablue** [comment]
I cannot reproduce the problem. FZH works for me in G2. Can you send me paths where it doesn’t work?

**Comment by guidoferreyra** [comment]
I've found the difference, in G2 I have to select the paths, in G1 don't. Sorry, my bad.

**Comment by mekkablue** [comment]
I just uploaded a new version. It should work again with an empty selection.

**Comment by guidoferreyra** [comment]
great!
