### ISSUE TITLE
Enable deletion of BCPs entirely when they both reside on their respective on-curve points

### ISSUE THREAD

**Issue by TrueTyper** [mekkablue/FixZeroHandles#3]
It would be great if you handle the case where:
if [x1, y1] == [x2, y2] and [x3, y3] == [x4, y4]:

to create a straight line from [x1, y1] to [x4, y4]

**Comment by mekkablue** [comment]
The latest update should do just that. Thanks for the suggestion.

**Comment by TrueTyper** [comment]
YOU ROCK RAINER!!! Thanks so much for the fast turn around. I’d say this is worth at least 2 beers next time I see you. :-)

Cheers,

Tom

On Jun 8, 2016, at 5:45 AM, Rainer Erich Scheichelbauer <notifications@github.com<mailto:notifications@github.com>> wrote:

The latest update should do just that. Thanks for the suggestion.
