### ISSUE TITLE
Problem with this plug in

### ISSUE THREAD

**Issue by zvikaro** [mekkablue/FixZeroHandles#6]
Got this error message after
![screen shot 2018-04-24 at 19 49 21](https://user-images.githubusercontent.com/18307787/39201882-0fa4694e-47f9-11e8-9675-78e2e9b8252f.png)
 upgrading to Glyphs 2.5 last week.

**Comment by mekkablue** [comment]
Uninstalling and reinstalling via _Window > Plugin Manager_ and restarting the app should fix this.

**Comment by zvikaro** [comment]
Thanks - this worked!

Best regards,

Zvika Rosenberg | Designer
Masterfont<http://www.masterfont.co.il/>

On 14 May 2018, at 11:34, Rainer Erich Scheichelbauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Uninstalling and reinstalling via Window > Plugin Manager and restarting the app should fix this.

**Comment by zvikaro** [comment]
Hi guys,

This happens again after 2 quiet days:

[cid:C6AA02E6-DD49-4BED-878C-6F2D49AD52E7@wework.com]


Process:               QuickLookSatellite [48359]
Path:                  /System/Library/Frameworks/QuickLook.framework/Versions/A/Resources/quicklookd.app/Contents/XPCServices/QuickLookSatellite.xpc/Contents/MacOS/QuickLookSatellite
Identifier:            QuickLookSatellite
Version:               5.0 (521.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           quicklookd [48355]
User ID:               501

PlugIn Path:             /Applications/Glyphs/Glyphs.app/Contents/Library/QuickLook/GlyphsQuickLook.qlgenerator/Contents/MacOS/GlyphsQuickLook
PlugIn Identifier:       com.schriftgestaltung.GlyphsQuickLook
PlugIn Version:          2.4 (10)

Date/Time:             2018-05-15 17:53:39.001 +0300
OS Version:            Mac OS X 10.12.6 (16G1314)
Report Version:        12
Anonymous UUID:        992E3FE6-7DD3-EE1C-5E96-BFE51C36B069

Sleep/Wake UUID:       289920EB-5DAC-43F4-AF80-C58442F28BB8

Time Awake Since Boot: 250000 seconds
Time Since Wake:       16000 seconds

System Integrity Protection: enabled

Crashed Thread:        1  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x8:
-->
    __TEXT                 000000010d1ae000-000000010d1b5000 [   28K] r-x/rwx SM=COW  /System/Library/Frameworks/QuickLook.framework/Versions/A/Resources/quicklookd.app/Contents/XPCServices/QuickLookSatellite.xpc/Contents/MacOS/QuickLookSatellite

Application Specific Information:
qlmanage --diag (null)
last threaded generator: com.schriftgestaltung.GlyphsQuickLook

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib         0x00007fffc580134a mach_msg_trap + 10
1   libsystem_kernel.dylib         0x00007fffc5800797 mach_msg + 55
2   com.apple.CoreFoundation       0x00007fffaff50434 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation       0x00007fffaff4f8c1 __CFRunLoopRun + 1361
4   com.apple.CoreFoundation       0x00007fffaff4f114 CFRunLoopRunSpecific + 420
5   com.apple.CoreFoundation       0x00007fffaff8eb91 CFRunLoopRun + 97
6   com.apple.XPCService           0x00007fffc3d0c5c7 xpc_service_main + 413
7   com.apple.quicklook.satellite 0x000000010d1afbb2 main + 95
8   libdyld.dylib                 0x00007fffc56da235 start + 1

Thread 1 Crashed:: Dispatch queue: com.apple.root.default-qos
0   com.schriftgestaltung.GlyphsQuickLook 0x000000010f594e4f ql_fgetln + 23
1   com.schriftgestaltung.GlyphsQuickLook 0x000000010f5672fd 0x10f560000 + 29437
2   com.schriftgestaltung.GlyphsQuickLook 0x000000010f5653e2 GenerateThumbnailForURL + 103
3   com.apple.QuickLookFramework   0x00007fffb5c7e2b7 _QLThumbnailRequestCallGenerator + 554
4   com.apple.quicklook.satellite 0x000000010d1b1434 0x10d1ae000 + 13364
5   com.apple.quicklook.satellite 0x000000010d1b27f3 0x10d1ae000 + 18419
6   com.apple.quicklook.satellite 0x000000010d1b119c 0x10d1ae000 + 12700
7   com.apple.QuickLookFramework   0x00007fffb5c7c5db ___process_element_block_invoke + 23
8   com.apple.QuickLookFramework   0x00007fffb5cb0fe4 QLTryCatchAndCrash(void () block_pointer) + 20
9   libdispatch.dylib             0x00007fffc56ad524 _dispatch_call_block_and_release + 12
10  libdispatch.dylib             0x00007fffc56a48fc _dispatch_client_callout + 8
11  libdispatch.dylib             0x00007fffc56a686e _dispatch_root_queue_drain + 917
12  libdispatch.dylib             0x00007fffc56a648c _dispatch_worker_thread3 + 99
13  libsystem_pthread.dylib       0x00007fffc58f35a2 _pthread_wqthread + 1299
14  libsystem_pthread.dylib       0x00007fffc58f307d start_wqthread + 13

[…] (shortened)

**Comment by mekkablue** [comment]
Hi Zvika:
this is a crash of the QuickLookSatellite background application, and has nothing to do with the FixZeroHandles plug-in. The QuickLook plug-in crashed probably when it tried to render a preview for a font in Finder, probably when you selected a font, .glyphs file, or UFO file, and pressed the space bar for a quick preview. Perhaps you can send Georg the font that makes the QL plug-in crash, and we can look into it.

**Comment by zvikaro** [comment]
Thanks you all for taking care of this annoying phenomena.
All I did was adjusting the outlines and fixing zero handles. (The font is in progress, not finished yet)


Here is the font:

[cid:bbce49e3-74f8-4751-84c1-bca62f800dd6@eurprd04.prod.outlook.com]

Best regards,

Zvika Rosenberg | Designer
Masterfont<http://www.masterfont.co.il/>

On 16 May 2018, at 10:14, Rainer Erich Scheichelbauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Zvika:
this is a crash of the QuickLookSatellite background application, and has nothing to do with the FixZeroHandles plug-in. The QuickLook plug-in crashed probably when it tried to render a preview for a font in Finder, probably when you selected a font, .glyphs file, or UFO file, and pressed the space bar for a quick preview. Perhaps you can send Georg the font that makes the QL plug-in crash, and we can look into it.
